<?xml version="1.0" ?>
<robot name="warthog" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include
        filename="$(find warthog_description)/urdf/wheel.urdf.xacro"
    />
    <xacro:include
        filename="$(find warthog_description)/urdf/diff_unit.urdf.xacro"
    />
    <xacro:include filename="$(find warthog_description)/urdf/utils.xacro" />
    <xacro:include
        filename="$(find warthog_description)/urdf/gazebo.urdf.xacro"
    />
    <xacro:include
        filename="$(find warthog_description)/urdf/ros2_control.urdf.xacro"
    />
    <xacro:include
        filename="$(find warthog_description)/urdf/body.urdf.xacro"
    />

    <!-- <xacro:property name="dummy_inertia" value="1e-09" /> -->
    <xacro:property name="PI" value="3.1415926535897931" />

    <xacro:property name="axle_x_offset" value="0.457367" />
    <xacro:property name="axle_y_offset" value="0.0" />
    <xacro:property name="axle_z_offset" value="-0.012977" />
    <!--
        Optional paint colors.
        Available colors:
        - yellow (default)
        - orange
        - olive
        - sand
    -->

    <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
    <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
    <material name="yellow"><color rgba="0.95 0.816 0.082 1.0" /></material>
    <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>
    <material name="white"><color rgba="0.9 0.9 0.9 1.0" /></material>
    <material name="red"><color rgba="0.9 0.0 0.0 1.0" /></material>

    <xacro:unless value="$(optenv WARTHOG_TRACKS 0)">
        <xacro:wheel prefix="front" side="left">
            <origin
                xyz="${axle_x_offset*1} ${axle_y_offset*1} ${axle_z_offset}"
                rpy="0 0 0"
            />
        </xacro:wheel>
        <xacro:wheel prefix="front" side="right">
            <origin
                xyz="${axle_x_offset*1} ${axle_y_offset*-1} ${axle_z_offset}"
                rpy="0 0 0"
            />
        </xacro:wheel>
        <xacro:wheel prefix="rear" side="left">
            <origin
                xyz="${axle_x_offset*-1} ${axle_y_offset*1} ${axle_z_offset}"
                rpy="0 0 0"
            />
        </xacro:wheel>
        <xacro:wheel prefix="rear" side="right">
            <origin
                xyz="${axle_x_offset*-1} ${axle_y_offset*-1} ${axle_z_offset}"
                rpy="0 0 0"
            />
        </xacro:wheel>
    </xacro:unless>

    <xacro:if value="$(optenv WARTHOG_TRACKS 0)">
        <xacro:track prefix="front" side="left">
            <origin
                xyz="${axle_x_offset*1} ${axle_y_offset*1} ${axle_z_offset}"
                rpy="0 0 0"
            />
        </xacro:track>
        <xacro:track prefix="front" side="right">
            <origin
                xyz="${axle_x_offset*1} ${axle_y_offset*-1} ${axle_z_offset}"
                rpy="0 0 0"
            />
        </xacro:track>
        <xacro:track prefix="rear" side="left">
            <origin
                xyz="${axle_x_offset*-1} ${axle_y_offset*1} ${axle_z_offset}"
                rpy="0 0 ${PI}"
            />
        </xacro:track>
        <xacro:track prefix="rear" side="right">
            <origin
                xyz="${axle_x_offset*-1} ${axle_y_offset*-1} ${axle_z_offset}"
                rpy="0 0 ${PI}"
            />
        </xacro:track>
    </xacro:if>

    <!-- instancia de unidad diferencial -->
    <xacro:diff_unit prefix="left" side="1" />
    <xacro:diff_unit prefix="right" side="-1" />

    <!-- sudo apt install ros-humble-ros2-controllers ros-humble-ros2-control sudo apt-get install ros-humble-ign-ros2-control-->
</robot>
