<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Para wheel_inertia -->
    <xacro:include filename="$(find warthog_description)/urdf/utils.xacro" />

    <xacro:property name="PI" value="3.1415926535897931" />

    <xacro:property name="wheel_radius" value="0.3" />
    <xacro:property name="wheel_width" value="0.25" />
    <xacro:property name="wheel_mass" value="15" />
    <xacro:property name="wheel_to_track_ratio" value="0.5962" />

    <!-- ======================================================= -->
    <!--                      Wheels                             -->
    <!-- ======================================================= -->

    <xacro:macro name="wheel" params="prefix side *joint_pose">
        <link name="${prefix}_${side}_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <xacro:wheel_inertia
                    m="${wheel_mass}"
                    r="${wheel_radius}"
                    h="${wheel_width}"
                />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${PI/2}" />
            <geometry>
            <mesh filename="package://warthog_description/meshes/wheel.stl" />
            </geometry>
            <material name="dark_grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        </link>

        <joint name="${prefix}_${side}_wheel_joint" type="continuous">
            <parent link="${side}_diff_unit_link" />
            <child link="${prefix}_${side}_wheel_link" />
            <xacro:insert_block name="joint_pose" />
            <axis xyz="0 1 0" />
        </joint>

        <gazebo reference="${prefix}_${side}_wheel_link">
            <selfCollide>false</selfCollide>
            <mu1>0.5</mu1>
            <mu2>0.5</mu2>
            <kp value="10000000.0" />
            <kd value="1.0" />
            <fdir1 value="1 0 0" />
            <material>Gazebo/DarkGrey</material>
        </gazebo>
        <transmission name="${prefix}_${side}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_${side}_wheel_joint">
                <hardwareInterface
                >hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_${side}_actuator">
                <hardwareInterface
                >hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- ======================================================= -->
    <!--                       Tracks                            -->
    <!-- ======================================================= -->

    <xacro:macro name="track" params="prefix side *joint_pose">
        <link name="${prefix}_${side}_track_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
            <mesh filename="package://warthog_description/meshes/tracks.dae" />
            </geometry>
            <material name="dark_grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
            <mesh
                        filename="package://warthog_description/meshes/tracks_collision.stl"
                    />
            </geometry>
        </collision>
        </link>
        <joint name="${prefix}_${side}_track_joint" type="fixed">
            <parent link="${side}_diff_unit_link" />
            <child link="${prefix}_${side}_track_link" />
            <xacro:insert_block name="joint_pose" />
            <axis xyz="0 1 0" />
        </joint>

        <!-- This adds wheels that rotate instead of tracks. -->
        <link name="${prefix}_${side}_wheel_link">
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
            <cylinder
                        radius="${wheel_radius*wheel_to_track_ratio}"
                        length="${wheel_width}"
                    />
            </geometry>
        </collision>
        </link>

        <joint name="${prefix}_${side}_wheel_joint" type="continuous">
            <parent link="${side}_diff_unit_link" />
            <child link="${prefix}_${side}_wheel_link" />
            <xacro:insert_block name="joint_pose" />
            <axis xyz="0 1 0" />
        </joint>

        <transmission name="${prefix}_${side}_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${prefix}_${side}_wheel_joint">
            <hardwareInterface
                >hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="${prefix}_${side}_actuator">
            <hardwareInterface
                >hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        </transmission>
    </xacro:macro>

</robot>
